[PDS-22/feat] 회의실 예약 개별 조회 API 생성
PLADI-ALM/PLADI-ALM-Server pull request #10
Opened 2023-09-23 12:42 UTC by psyeon1120

## ✈️ 지라 티켓
- [PDS-22](https://pladi-alm.atlassian.net/browse/PDS-2) 회의실 예약 개별 조회 API

<br>

## 👾 작업 내용
- 회의실 예약 개별 조회 API 생성
- booking 도메인 폴더 생성

<br>

## 📸 스크린샷

<br>

## 🎸 기타 사항
- BaseEntity에 있는 where절이 적용이 안되어서 각 엔티티에 하나씩 넣어줬습니다.(+img는 hard delete할 예정이라서 안 넣었습니다)

2023-09-23 13:33 UTC, chaerlo127 approved these changes
굳굳

2023-09-23 15:07 UTC, sojungpp requested changes
`@Where` 깔끔 정리 감사합니다 - !!
+) 혹시 담에 어노테이션 정리나 폴더 이동 등 커밋 따로 나눠서 해주시면, 나중에 찾아보거나 리뷰할 때 보기 더 편할 것 같은데 어때요..! 부탁🤍

2023-09-23 15:07 UTC, sojungpp commented on src/main/java/com/example/pladialmserver/booking/dto/response/OfficeBookingDetailRes.java
> +    }
![스크린샷 2023-09-24 오전 12 00 00](https://github.com/PLADI-ALM/PLADI-ALM-Server/assets/90022940/18c84b54-99e5-4fec-90d3-f378b375e4e2)

해당 화면에서 필요한 API 맞나요? 맞으면 회의실 사진도 추가해야 할 것 같습니다!

2023-09-23 15:08 UTC, sojungpp approved these changes

2023-09-24 06:53 UTC, dangnak2 approved these changes

2023-09-24 06:53 UTC, dangnak2 commented on src/main/java/com/example/pladialmserver/office/entity/Facility.java
> +@Where(clause = "is_enable = true")
DAO 가독성 더 좋아지는것 같네요 ㅎㅎ

2023-09-24 06:54 UTC, merged