[PDS-150/refactor] 장비 목록 조회 Jpql에서 Query Dsl로 리펙토링
PLADI-ALM/PLADI-ALM-Server pull request #145
Opened 2023-10-31 14:38 UTC by leeseunghakhello

… 하나만 입력해도 조회되게 수정

## ✈️ 지라 티켓
- [PDS-150](https://pladi-alm.atlassian.net/browse/PDS-150) 장비 목록 조회 Jpql에서 Query Dsl로 리펙토링 / 장비 이름, 날짜와 시간 둘중에 하나만 입력하더라도 조회되도록 수정

<br>

## 👾 작업 내용
- 

<br>

## 📸 스크린샷

<br>

## 🎸 기타 사항
-

2023-10-31 16:21 UTC, sojungpp commented on src/main/java/com/example/pladialmserver/resource/repository/ResourceRepositoryImpl.java
> +                            resource.resourceId.notIn(bookedResourceIds))
유레카,,

2023-10-31 16:23 UTC, sojungpp requested changes
17줄을 1줄로 줄여버리셨다.

2023-10-31 16:23 UTC, sojungpp commented on src/main/java/com/example/pladialmserver/booking/repository/resourceBooking/ResourceBookingRepositoryImpl.java
> +    }
여기에 resourceBooking 상태가 취소인 건 빼고 가져와야할 것 같아요-!

2023-11-01 00:32 UTC, chaerlo127 approved these changes
아따 최고다🙌

2023-11-01 00:32 UTC, chaerlo127 commented on src/main/java/com/example/pladialmserver/resource/repository/ResourceRepositoryImpl.java
> +                            resource.isActive.isTrue())
아래랑 겹치는 코드가 있는거 같아서 공통적인건 이렇게 빼도 좋을 것 같아욤

https://github.com/PLADI-ALM/PLADI-ALM-Server/blob/b9d59e5f7ca8968acfc3e95158b74ea34b54dc06/src/main/java/com/example/pladialmserver/user/repository/user/UserRepositoryImpl.java#L31-L35

2023-11-01 00:32 UTC, chaerlo127 commented on src/main/java/com/example/pladialmserver/resource/service/ResourceService.java
> -        Page<Resource> allResources;
👏

2023-11-01 00:32 UTC, chaerlo127 commented on src/main/java/com/example/pladialmserver/resource/repository/ResourceRepositoryImpl.java
> +            results = jpaQueryFactory
요런 분기문도` ResourceBookingRepositoryImpl.java` 에 있는 resourceNameContaining 처럼 처리하지 않은 이유가 있을까요?

2023-11-01 00:32 UTC, chaerlo127 commented on src/main/java/com/example/pladialmserver/resource/repository/ResourceRepositoryImpl.java
> +        }
요건 서비스 단에서 불러와서 파라미터로 넘겨주는건 어떨까요오

2023-11-01 10:34 UTC, sojungpp approved these changes

2023-11-01 12:19 UTC, merged