[PDS-102/feat] 관리자 회의실 예약 목록 조회 API
PLADI-ALM/PLADI-ALM-Server pull request #47
Opened 2023-10-06 10:00 UTC by leeseunghakhello

## ✈️ 지라 티켓
- [PDS-102](https://pladi-alm.atlassian.net/browse/PDS-102) 관리자 회의실 예약 목록 조회 API

<br>

## 👾 작업 내용
- 관리자 회의실 예약 목록 조회 API

<br>

## 📸 스크린샷
<전체조회>
<img width="343" alt="스크린샷 2023-10-06 오후 6 58 54" src="https://github.com/PLADI-ALM/PLADI-ALM-Server/assets/90025978/0720069b-9348-411e-9bc2-cbfb1bf7a3a1">
<예약중 조회>
<img width="342" alt="스크린샷 2023-10-06 오후 6 59 25" src="https://github.com/PLADI-ALM/PLADI-ALM-Server/assets/90025978/8027ec06-80e7-473a-b384-67c75652acc7">
<예외처리>
<img width="536" alt="스크린샷 2023-10-06 오후 6 58 31" src="https://github.com/PLADI-ALM/PLADI-ALM-Server/assets/90025978/71110f0b-ecaf-4431-bce7-a09bde41072a">

<br>

## 🎸 기타 사항
-

2023-10-06 11:44 UTC, psyeon1120 requested changes

2023-10-06 11:44 UTC, psyeon1120 commented on src/main/java/com/example/pladialmserver/admin/AdminController.java
> +            @Parameter(description = "회의실 예약 상태 카테고리 선택", example = "'BOOKED' / 'USING'") @RequestParam(required = false) String bookingStatus,
관리자 회의실 예약 내역은 그냥 예약중, 사용중만 전체로 보내주시면 됩니당
status 받는거는 없애면 될것 같아요!

2023-10-07 08:50 UTC, dangnak2 approved these changes
고생하셨습니다!

2023-10-08 05:42 UTC, chaerlo127 approved these changes

2023-10-08 06:23 UTC, sojungpp requested changes

2023-10-08 06:23 UTC, sojungpp commented on src/main/java/com/example/pladialmserver/admin/AdminController.java
> +@RequestMapping("/Admin")
URL 소문자 통일 어때요 `/Admin` ->` /admin`

2023-10-08 06:23 UTC, sojungpp commented on src/main/java/com/example/pladialmserver/admin/AdminService.java
> +            );
정렬 한 번만 추가해주세요 !! 
![스크린샷 2023-10-08 오후 3 22 55](https://github.com/PLADI-ALM/PLADI-ALM-Server/assets/90022940/c47f0348-6f4a-4b6c-a570-1a0ae9e1154b)

2023-10-08 06:26 UTC, chaerlo127 commented on src/main/java/com/example/pladialmserver/admin/AdminController.java
> +    @GetMapping
uri 수정도 필요합니다!

2023-10-08 12:39 UTC, psyeon1120 approved these changes

2023-10-08 12:40 UTC, merged